### ISSUE TITLE
Folder "mixturevqvae.prior.bridge" is missing

### ISSUE THREAD

**Issue by QichenZheng** [maxjcohen/diffusion-bridges#4]
An error occurred in the following code in toy_example.ipynb.
from mixturevqvae.prior.bridge.toy.toy_diffusion import Net

Error message:
No module named "mixturevqvae.prior.bridge"

I checked the files on github, and it seems that in the. /mixturevqvae/prior folder, there is no folder named "bridge." Is it missing?

**Comment by QichenZheng** [comment]
@maxjcohen @charlesollion

**Comment by maxjcohen** [comment]
Hi, the notebook still relied on some old code, which had been removed. This should fix it.
